In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("/content/Airbnb_Open_Data.csv")
data

/tmp/ipython-input-21097655.py:1: DtypeWarning: Columns (25) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/content/Airbnb_Open_Data.csv")

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [3]:
data.shape

(102599, 26)

In [4]:
data.head(10)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
5,1004098,Large Cozy 1 BR Apartment In Midtown East,45498551794,verified,Michelle,Manhattan,Murray Hill,40.74767,-73.97500,United States,...,$115,3.0,74.0,6/22/2019,0.59,3.0,1.0,374.0,"No smoking, please, and no drugs.",NaN
6,1004650,BlissArtsSpace!,61300605564,NaN,Alberta,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$14,45.0,49.0,10/5/2017,0.40,5.0,1.0,224.0,Please no shoes in the house so bring slippers...,NaN
7,1005202,BlissArtsSpace!,90821839709,unconfirmed,Emma,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,United States,...,$212,45.0,49.0,10/5/2017,0.40,5.0,1.0,219.0,House Guidelines for our BnB We are delighted ...,NaN
8,1005754,Large Furnished Room Near B'way,79384379533,verified,Evelyn,Manhattan,Hell's Kitchen,40.76489,-73.98493,United States,...,$204,2.0,430.0,6/24/2019,3.47,3.0,1.0,180.0,- Please clean up after yourself when using th...,NaN
9,1006307,Cozy Clean Guest Room - Family Apt,75527839483,unconfirmed,Carl,Manhattan,Upper West Side,40.80178,-73.96723,United States,...,$58,2.0,118.0,7/21/2017,0.99,5.0,1.0,375.0,NO SMOKING OR PETS ANYWHERE ON THE PROPERTY 1....,NaN

In [5]:
print(data['price'].value_counts())
print("======================================================================================================================")
print(data['service fee'].value_counts())
data['price']

price
$206       137
$1,056     132
$481       129
$833       128
$573       127
          ...
$369        58
$923        57
$786        54
$89         53
$187        52
Name: count, Length: 1151, dtype: int64
======================================================================================================================
service fee
$41      526
$216     524
$81      519
$177     518
$57      513
        ...
$73      386
$58      384
$67      381
$10      267
$240     248
Name: count, Length: 231, dtype: int64

0           $966
1           $142
2           $620
3           $368
4           $204
           ...
102594      $844
102595      $837
102596      $988
102597      $546
102598    $1,032
Name: price, Length: 102599, dtype: object

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [7]:
data.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [8]:
data.duplicated().sum()

np.int64(541)

In [9]:
data.drop_duplicates(inplace=True)

In [10]:
data.isna().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            404
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       400
number of reviews                    183
last review                        15832
reviews per month                  15818
review rate number                   319
calculated host listings count       319
availability 365                     448
house_rules                        51842
license                           102056
dtype: int64

In [11]:
for column in data.columns:
    if data[column].isnull().sum() != 0:
        print("=======================================================")
        print(f"{column} ==> Missing Values : {data[column].isnull().sum()}, dtypes : {data[column].dtypes}")

=======================================================
NAME ==> Missing Values : 250, dtypes : object
=======================================================
host_identity_verified ==> Missing Values : 289, dtypes : object
=======================================================
host name ==> Missing Values : 404, dtypes : object
=======================================================
neighbourhood group ==> Missing Values : 29, dtypes : object
=======================================================
neighbourhood ==> Missing Values : 16, dtypes : object
=======================================================
lat ==> Missing Values : 8, dtypes : float64
=======================================================
long ==> Missing Values : 8, dtypes : float64
=======================================================
country ==> Missing Values : 532, dtypes : object
=======================================================
country code ==> Missing Values : 131, dtypes : object
=======================================================
instant_bookable ==> Missing Values : 105, dtypes : object
=======================================================
cancellation_policy ==> Missing Values : 76, dtypes : object
=======================================================
Construction year ==> Missing Values : 214, dtypes : float64
=======================================================
price ==> Missing Values : 247, dtypes : object
=======================================================
service fee ==> Missing Values : 273, dtypes : object
=======================================================
minimum nights ==> Missing Values : 400, dtypes : float64
=======================================================
number of reviews ==> Missing Values : 183, dtypes : float64
=======================================================
last review ==> Missing Values : 15832, dtypes : object
=======================================================
reviews per month ==> Missing Values : 15818, dtypes : float64
=======================================================
review rate number ==> Missing Values : 319, dtypes : float64
=======================================================
calculated host listings count ==> Missing Values : 319, dtypes : float64
=======================================================
availability 365 ==> Missing Values : 448, dtypes : float64
=======================================================
house_rules ==> Missing Values : 51842, dtypes : object
=======================================================
license ==> Missing Values : 102056, dtypes : object

In [12]:
data.columns

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='object')

In [13]:
for col in ['price', 'service fee']:
    if col in data.columns:
        data[col] = data[col].str.replace('$','', regex=False).str.replace(',','', regex=False)
        data[col] = pd.to_numeric(data[col], errors='coerce')
        data[col] = data[col].fillna(data[col].median())

In [14]:
data.columns = data.columns.str.strip()
data.columns = data.columns.str.lower().str.replace(' ', '_')

In [15]:
data.columns = data.columns.str.strip().str.lower().str.replace(' ', '_')

data = data.drop(columns=['house_rules', 'license', 'host_name'], errors='ignore')

cat_cols = ['name','host_identity_verified','neighbourhood_group','neighbourhood',
            'instant_bookable','cancellation_policy','country','country_code','room_type']

for col in cat_cols:
    if col in data.columns:

        if data[col].dtype == 'object':
            data[col] = data[col].fillna(data[col].mode()[0])
        else:
            data[col] = data[col].fillna('unverified')


numeric_cols = [
    'lat','long','construction_year','price','service_fee','minimum_nights',
    'number_of_reviews','reviews_per_month','review_rate_number',
    'calculated_host_listings_count','availability_365'
]

for col in numeric_cols:
    if col in data.columns:

        data[col] = pd.to_numeric(data[col], errors='coerce')

        data[col] = data[col].fillna(data[col].median())


if 'last_review' in data.columns:
    data['last_review'] = pd.to_datetime(data['last_review'], errors='coerce')
    data['last_review'] = data['last_review'].fillna(pd.to_datetime('2000-01-01'))


print("Missing values after preprocessing:")
print(data.isnull().sum())

data = data.reset_index(drop=True)

/tmp/ipython-input-184961136.py:12: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data[col] = data[col].fillna(data[col].mode()[0])

Missing values after preprocessing:
id                                0
name                              0
host_id                           0
host_identity_verified            0
neighbourhood_group               0
neighbourhood                     0
lat                               0
long                              0
country                           0
country_code                      0
instant_bookable                  0
cancellation_policy               0
room_type                         0
construction_year                 0
price                             0
service_fee                       0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
review_rate_number                0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [16]:
data = data.drop(columns=['name'], errors='ignore')

In [17]:
data.isna().sum()

id                                0
host_id                           0
host_identity_verified            0
neighbourhood_group               0
neighbourhood                     0
lat                               0
long                              0
country                           0
country_code                      0
instant_bookable                  0
cancellation_policy               0
room_type                         0
construction_year                 0
price                             0
service_fee                       0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
review_rate_number                0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102058 entries, 0 to 102057
Data columns (total 22 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102058 non-null  int64
 1   host_id                         102058 non-null  int64
 2   host_identity_verified          102058 non-null  object
 3   neighbourhood_group             102058 non-null  object
 4   neighbourhood                   102058 non-null  object
 5   lat                             102058 non-null  float64
 6   long                            102058 non-null  float64
 7   country                         102058 non-null  object
 8   country_code                    102058 non-null  object
 9   instant_bookable                102058 non-null  bool
 10  cancellation_policy             102058 non-null  object
 11  room_type                       102058 non-null  object
 12  construction_year               102058 non-null  float64
 13  price                           102058 non-null  float64
 14  service_fee                     102058 non-null  float64
 15  minimum_nights                  102058 non-null  float64
 16  number_of_reviews               102058 non-null  float64
 17  last_review                     102058 non-null  datetime64[ns]
 18  reviews_per_month               102058 non-null  float64
 19  review_rate_number              102058 non-null  float64
 20  calculated_host_listings_count  102058 non-null  float64
 21  availability_365                102058 non-null  float64
dtypes: bool(1), datetime64[ns](1), float64(11), int64(2), object(7)
memory usage: 16.4+ MB

In [19]:
data.shape

(102058, 22)

In [20]:
data.head()

,id,host_id,host_identity_verified,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,...,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,1001254,80014485718,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,...,2020.0,966.0,193.0,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0
1,1002102,52335172823,verified,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,...,2007.0,142.0,28.0,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0
2,1002403,78829239556,unconfirmed,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,...,2005.0,620.0,124.0,3.0,0.0,2000-01-01,0.74,5.0,1.0,352.0
3,1002755,85098326012,unconfirmed,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,...,2005.0,368.0,74.0,30.0,270.0,2019-07-05,4.64,4.0,1.0,322.0
4,1003689,92037596077,verified,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,...,2009.0,204.0,41.0,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0

In [21]:
data = data.drop(columns=['id','host_id'], errors='ignore')

In [22]:
data

,host_identity_verified,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,construction_year,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365
0,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,966.0,193.0,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0
1,verified,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,142.0,28.0,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0
2,unconfirmed,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,620.0,124.0,3.0,0.0,2000-01-01,0.74,5.0,1.0,352.0
3,unconfirmed,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,368.0,74.0,30.0,270.0,2019-07-05,4.64,4.0,1.0,322.0
4,verified,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,204.0,41.0,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102053,unconfirmed,Brooklyn,Flatbush,40.64945,-73.96108,United States,US,True,moderate,Private room,2012.0,696.0,125.0,7.0,12.0,2019-03-27,0.44,5.0,1.0,0.0
102054,verified,Brooklyn,Bushwick,40.69872,-73.92718,United States,US,False,flexible,Private room,2012.0,909.0,125.0,1.0,19.0,2017-08-31,0.72,3.0,2.0,0.0
102055,verified,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,US,True,moderate,Entire home/apt,2012.0,387.0,125.0,2.0,50.0,2019-06-26,3.12,4.0,2.0,235.0
102056,unconfirmed,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,2012.0,848.0,125.0,2.0,0.0,2000-01-01,0.74,1.0,1.0,0.0
102057,verified,Manhattan,Harlem,40.81315,-73.94747,United States,US,False,flexible,Entire home/apt,2011.0,1128.0,125.0,4.0,22.0,2019-06-15,0.85,4.0,1.0,238.0

In [23]:
data['property_age'] = 2026-data['construction_year'] . astype(int)
data = data.drop(columns=['construction_year'] , errors='ignore')

In [24]:
data.head()

,host_identity_verified,neighbourhood_group,neighbourhood,lat,long,country,country_code,instant_bookable,cancellation_policy,room_type,price,service_fee,minimum_nights,number_of_reviews,last_review,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,property_age
0,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,966.0,193.0,10.0,9.0,2021-10-19,0.21,4.0,6.0,286.0,6
1,verified,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,142.0,28.0,30.0,45.0,2022-05-21,0.38,4.0,2.0,228.0,19
2,unconfirmed,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,620.0,124.0,3.0,0.0,2000-01-01,0.74,5.0,1.0,352.0,21
3,unconfirmed,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,368.0,74.0,30.0,270.0,2019-07-05,4.64,4.0,1.0,322.0,21
4,verified,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,204.0,41.0,10.0,9.0,2018-11-19,0.10,3.0,1.0,289.0,17

In [25]:
data['days_since_last_review'] = (pd.to_datetime('2026-02-14') - data['last_review']).dt.days
data = data.drop(columns=['last_review'], errors='ignore')

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102058 entries, 0 to 102057
Data columns (total 20 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   host_identity_verified          102058 non-null  object
 1   neighbourhood_group             102058 non-null  object
 2   neighbourhood                   102058 non-null  object
 3   lat                             102058 non-null  float64
 4   long                            102058 non-null  float64
 5   country                         102058 non-null  object
 6   country_code                    102058 non-null  object
 7   instant_bookable                102058 non-null  bool
 8   cancellation_policy             102058 non-null  object
 9   room_type                       102058 non-null  object
 10  price                           102058 non-null  float64
 11  service_fee                     102058 non-null  float64
 12  minimum_nights                  102058 non-null  float64
 13  number_of_reviews               102058 non-null  float64
 14  reviews_per_month               102058 non-null  float64
 15  review_rate_number              102058 non-null  float64
 16  calculated_host_listings_count  102058 non-null  float64
 17  availability_365                102058 non-null  float64
 18  property_age                    102058 non-null  int64
 19  days_since_last_review          102058 non-null  int64
dtypes: bool(1), float64(10), int64(2), object(7)
memory usage: 14.9+ MB

In [27]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

In [28]:
numeric_cols = [
    'lat','long','price','service_fee','minimum_nights','number_of_reviews',
    'reviews_per_month','review_rate_number','calculated_host_listings_count',
    'availability_365','property_age','days_since_last_review'
]


categorical_cols = [
    'host_identity_verified','neighbourhood_group','neighbourhood',
    'country','country_code','instant_bookable','cancellation_policy','room_type'
]


preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_cols),
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'), categorical_cols)
    ],
    sparse_threshold=0
)


X_array = preprocessor.fit_transform(data)


cat_features = preprocessor.named_transformers_['cat'].get_feature_names_out(categorical_cols)
all_columns = numeric_cols + list(cat_features)


data_preprocessed = pd.DataFrame(X_array, columns=all_columns)
print(data_preprocessed.shape)
data_preprocessed.head()

(102058, 248)

,lat,long,price,service_fee,minimum_nights,number_of_reviews,reviews_per_month,review_rate_number,calculated_host_listings_count,availability_365,...,neighbourhood_Woodhaven,neighbourhood_Woodlawn,neighbourhood_Woodrow,neighbourhood_Woodside,instant_bookable_True,cancellation_policy_moderate,cancellation_policy_strict,room_type_Hotel room,room_type_Private room,room_type_Shared room
0,-1.443276,-0.458942,1.028303,1.026028,0.061962,-0.373096,-0.657291,0.562778,-0.059447,1.073910,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,0.456993,-0.689248,-1.459099,-1.465033,0.716452,0.353668,-0.552561,0.562778,-0.183601,0.644801,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,1.448935,0.156621,-0.016164,-0.015688,-0.167109,-0.554787,-0.330779,1.342100,-0.214639,1.562207,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,-0.769149,-0.204191,-0.776874,-0.770556,0.716452,4.895944,2.071857,0.562778,-0.214639,1.340254,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
4,1.260753,0.114399,-1.271940,-1.268768,0.061962,-0.373096,-0.725058,-0.216544,-0.214639,1.096106,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [29]:
!pip install catboost --upgrade
from catboost import CatBoostRegressor, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


target = 'price'
X = data.drop(columns=[target])
y = data[target]


cat_features = [col for col in X.columns if X[col].dtype == 'object' or X[col].dtype == 'bool']


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=6,
    eval_metric='RMSE',
    random_seed=42,
    verbose=100
)


model.fit(X_train, y_train, cat_features=cat_features, eval_set=(X_test, y_test), use_best_model=True)


y_pred = model.predict(X_test)


rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("RMSE:", rmse)
print("R2 Score:", r2_score(y_test, y_pred))

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.8)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24->catboost) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.3)
0:	learn: 315.2923983	test: 316.0148333	best: 316.0148333 (0)	total: 164ms	remaining: 2m 44s
100:	learn: 21.4230484	test: 25.6507199	best: 25.6507199 (100)	total: 7.91s	remaining: 1m 10s
200:	learn: 20.9464746	test: 25.4318789	best: 25.4317147 (196)	total: 16.5s	remaining: 1m 5s
300:	learn: 20.6864574	test: 25.3368565	best: 25.3368565 (300)	total: 24.7s	remaining: 57.3s
400:	learn: 20.4742945	test: 25.2829471	best: 25.2814721 (390)	total: 31.4s	remaining: 46.9s
500:	learn: 20.3216119	test: 25.2991436	best: 25.2741776 (416)	total: 39.2s	remaining: 39.1s
600:	learn: 20.2006432	test: 25.3105710	best: 25.2741776 (416)	total: 46s	remaining: 30.5s
700:	learn: 20.0618667	test: 25.3415132	best: 25.2741776 (416)	total: 54.4s	remaining: 23.2s
800:	learn: 19.9105521	test: 25.3587404	best: 25.2741776 (416)	total: 1m 10s	remaining: 17.4s
900:	learn: 19.7894320	test: 25.3716953	best: 25.2741776 (416)	total: 1m 26s	remaining: 9.54s
999:	learn: 19.6226332	test: 25.4171672	best: 25.2741776 (416)	total: 1m 38s	remaining: 0us

bestTest = 25.27417756
bestIteration = 416

Shrink model to first 417 iterations.
RMSE: 25.274177558062448
R2 Score: 0.9941990869225935